name: Build and Rename APK with Versioning

on:
  push:
    branches:
      - master # Or any branch you want the action to run on

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 17

      - name: Grant execute permissions for gradlew
        run: chmod +x ./gradlew

      - name: Build Debug APK
        run: ./gradlew assembleDebug

      # Extract version details from build.gradle and rename APK
      - name: Rename APK with versioning
        run: |
          VERSION_NAME=$(grep "versionName" app/build.gradle | awk '{print $2}' | tr -d \")
          VERSION_CODE=$(grep "versionCode" app/build.gradle | awk '{print $2}')
          mv app/build/outputs/apk/debug/app-debug.apk app/build/outputs/apk/debug/app-$VERSION_NAME-$VERSION_CODE.apk

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: app-versioned-debug
          path: app/build/outputs/apk/debug/app-*.apk
